org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
maven_group = com.mystic
archives_base_name = holographic-renders
mod_id=holographic_renders
mod_authors=Mysticpasta1
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.215
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
mod_name=holographic_renders
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.mystic
mod_description=
jei_version=19.25.1.328